PROJECT(PixelEd)

SET(QT_USE_QTNETWORK TRUE)
SET(QT_USE_QTSCRIPT TRUE)
SET(CMAKE_BUILD_TYPE Release)
SET(CMAKE_AUTOMOC ON)

if (QT6_BUILD)
  find_package(Qt6Core REQUIRED)
  find_package(Qt6Gui REQUIRED)
  find_package(Qt6Xml REQUIRED)
  find_package(Qt6Qml REQUIRED)
  find_package(Qt6Widgets REQUIRED)
  find_package(Qt6Network REQUIRED)
  find_package(Qt6 REQUIRED COMPONENTS OpenGLWidgets)
  set(QT_INCLUDES ${Qt6Gui_INCLUDE_DIRS} ${Qt6Qml_INCLUDE_DIRS} ${Qt6Widgets_INCLUDE_DIRS} ${Qt6Network_INCLUDE_DIRS} ${Qt6Xml_INCLUDE_DIRS} ${Qt6Svg_INCLUDE_DIRS} ${Qt6OpenGLWidgets_INCLUDE_DIRS})
elseif(QT5_BUILD)
  find_package(Qt5Core REQUIRED)
  find_package(Qt5Widgets REQUIRED)
  find_package(Qt5Multimedia REQUIRED)
  find_package(Qt5Xml REQUIRED)
  find_package(Qt5Gui REQUIRED)
  find_package(Qt5Network REQUIRED)
  set(QT_INCLUDES ${Qt5Gui_INCLUDE_DIRS} ${Qt5Widgets_INCLUDE_DIRS} ${Qt5Network_INCLUDE_DIRS})
  include_directories(${QT_INCLUDES})
else()
  find_package(Qt4 REQUIRED)
endif()

file (GLOB ui "*.ui")
file (GLOB headers "*.h" "*/*.h")
file (GLOB src "*.cpp" "*/*.cpp")
file (GLOB resources "*.qrc")

if (QT6_BUILD)
    QT6_WRAP_CPP(pixeled_HEADERS_MOC ${pixeled_HEADERS})
    QT6_WRAP_UI(pixeled_FORMS_HEADERS ${ui})
    QT6_ADD_RESOURCES(pixeled_RESOURCES_RCC ${resources})
elseif(QT5_BUILD)
    QT5_WRAP_CPP(pixeled_HEADERS_MOC ${pixeled_HEADERS})
    QT5_WRAP_UI(pixeled_FORMS_HEADERS ${ui})
    QT5_ADD_RESOURCES(pixeled_RESOURCES_RCC ${resources})
else()
    QT4_WRAP_CPP(pixeled_HEADERS_MOC ${pixeled_HEADERS})
    QT4_WRAP_UI(pixeled_FORMS_HEADERS ${ui})
    QT4_ADD_RESOURCES(pixeled_RESOURCES_RCC ${resources})
endif()

if (NOT QT5_BUILD AND NOT QT6_BUILD)
  INCLUDE(${QT_USE_FILE})
endif()

ADD_DEFINITIONS(${QT_DEFINITIONS})
ADD_DEFINITIONS( -DQT_USE_QSTRINGBUILDER )

ADD_EXECUTABLE(pixeled ${src} ${pixeled_HEADERS_MOC} ${headers} ${pixeled_RESOURCES_RCC} ${pixeled_FORMS_HEADERS})
if (QT5_BUILD)
    TARGET_LINK_LIBRARIES(pixeled Qt5::Core Qt5::Multimedia Qt5::Gui Qt5::Widgets Qt5::Xml)
elseif(QT6_BUILD)
    TARGET_LINK_LIBRARIES(pixeled Qt6::Core Qt6::Network Qt6::Xml Qt6::Widgets Qt6::OpenGLWidgets)
endif()
TARGET_LINK_LIBRARIES(pixeled pixelengine ${QT_LIBRARIES})
if (NOT WIN32)
    INSTALL(TARGETS pixeled RUNTIME DESTINATION bin)
endif()
INCLUDE_DIRECTORIES(${CMAKE_CURRENT_BINARY_DIR})
INCLUDE_DIRECTORIES("../PixelEngine/src/")
